bump_version: null
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-metabolt_logo_light.png
    - docs/images/nf-core-metabolt_logo_light.png
    - docs/images/nf-core-metabolt_logo_dark.png
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-metabolt_logo_light.png
    - docs/images/nf-core-metabolt_logo_light.png
    - docs/images/nf-core-metabolt_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/workflows/branch.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
nf_core_version: 3.2.0
org_path: null
repository_type: pipeline
template:
  author: Muhammad Muneeb Nasir
  description: Lightning fast & automated metagenomic pipeline powered by Nextflow
  force: true
  is_nfcore: false
  name: metabolt
  org: MDL
  outdir: .
  skip_features: null
  version: "1.0"
update: null
